# Generated by Django 5.1.2 on 2024-11-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='realName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='realName',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero')),
                ('reporter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hero.reporter')),
            ],
        ),
    ]
