# Generated by Django 5.1.1 on 2024-10-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('heropk', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('realName', models.CharField(max_length=200)),
                ('strength1', models.CharField(max_length=200)),
                ('strength2', models.CharField(max_length=200)),
                ('strength3', models.CharField(max_length=200)),
                ('weakness1', models.CharField(max_length=200)),
                ('weakness2', models.CharField(max_length=200)),
                ('weakness3', models.CharField(max_length=200)),
                ('imagePath', models.CharField(max_length=200)),
            ],
        ),
    ]
